version: 0.2

env:
  variables:
    S3_BUCKET: ""

phases:
  build:
    commands:
      - cd hello && npm install && npm test
      - cd ..
      - cd good_bye && npm install && npm test
      - cd ..
  post_build:
    commands:
      - SCM_VERSION="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - printf '{"Parameters":{"ScmVersion":"%s"}}' $SCM_VERSION > parameters.json
      - aws cloudformation package --template template.yaml --s3-bucket $S3_BUCKET --output-template stack.yaml

artifacts:
  files:
    - stack.yaml
    - parameters.json
